---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This component installs the onnxruntime"
ComponentPublisher: "{COMPONENT_AUTHOR}"
Manifests:
  - Platform:
      os: all
    Lifecycle:
      Install:
        RequiresPrivilege: "true"
        script: "pip3 install awsiotsdk onnxruntime==1.15.1 opencv-python-headless"
